[App]
Name = "challenge-wildfires-submission-htb"
Version = "1.0"
Title = "Wildfire Challenge Submission Smoke Detection - HTB"
Description = "Wildfire Challenge Submission Description HTB."
LongDescription = "about.md"
Tags = ["WILDFIRES"]

[Runtime]
Module = "src.app"
MemoryLimit = "10Gi"
MemoryReservation = "10Gi"
